import { components } from "./apiSchema.generated";

export interface BranchModel {
  id: number;
  name: string;
  isDefault: boolean;
  isProtected: boolean;
}

/**
 * This file contains endpoints that are not generated by openapi-typescript but are still needed for the app.
 */
export interface customPaths {
  "/v2/projects/{projectId}": {
    /**
     * Get project info
     * @description Returns info about a project
     */
    get: operations["get"];
  };
  "/v2/projects/{projectId}/branches": {
    /**
     * Get branches
     * @description Returns all branches for a project
     */
    get: operations["getBranches"];
  };
}

export interface operations {
  /**
   * Get project info
   * @description Returns info about a project
   */
  get: {
    parameters: {
      path: {
        projectId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectModel"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** @description Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  /**
   * Get branches
   * @description Returns all branches for a project
   */
  getBranches: {
    parameters: {
      path: {
        projectId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": {
            _embedded?: {
              branches?: BranchModel[];
            };
          };
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** @description Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
}
